Use `subprocess` instead of `commands`
Currently, arugments containing whitespace get mangled by `''.join(argv[1:])`. By using `subprocess.check_output` instead of `commands.getoutput` this issue is resolved.

```
> python vtctrans.py -Dvarnishd="varnishd -p default_ttl=0 -p vcc_allow_inline_c=true -p vcc_err_unref=false" -k test.vtc
varnishtest: invalid option -- 'p'
usage: varnishtest [options] file ...
    -b size                      # Set internal buffer size (default: 512K)
    -D name=val                  # Define macro
    -i                           # Find varnishd in build tree
    -j jobs                      # Run this many tests in parallel
    -k                           # Continue on test failure
    -L                           # Always leave temporary vtc.*
    -l                           # Leave temporary vtc.* if test fails
    -n iterations                # Run tests this many times
    -q                           # Quiet mode: report only failures
    -t duration                  # Time tests out after this long
    -v                           # Verbose mode: always report test log
    -W                           # Enable the witness facility for locking

Traceback (most recent call last):
  File "vtctrans.py", line 791, in <module>
    main()
  File "vtctrans.py", line 14, in main
    if(r[0]['result'] != 'passed'):
TypeError: 'NoneType' object has no attribute '__getitem__'
```